import { DM_Sans, Montserrat, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat", // hanya untuk class tertentu
  subsets: ["latin"],
});

const nunito = DM_Sans({
  variable: "--font-nunito", // digunakan sebagai default
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["devanagari"],
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${montserrat.variable}
          ${nunito.variable}
          ${poppins.variable}
          ${playfair.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
